rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby
  - rbx
notifications:
  email:
    - fabricius@podio.com
    - auchenberg@podio.com
    - haugstrup@podio.com
    - daniel@podio.com
    - munz@podio.com
